// Test generated by RoostGPT for test roost-test using AI Type Azure Open AI and AI Model roost-gpt4-32k

package com.mycompany.app;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class App_getMessage_cebf167bb8_Test {

    private App app;
    private static final String MESSAGE = "Hello, World!"; // TODO: Substitute this message with a real one for testing.

    @BeforeEach
    public void setup() {
        app = new App();
    }

    @Test
    public void testGetMessageReturnsCorrectMessage() {
        Assertions.assertEquals(MESSAGE, app.getMessage());
    }

    @Test
    public void testGetMessageReturnsNonEmptyMessage() {
        Assertions.assertFalse(app.getMessage().isEmpty());
    }
}
